Repository thoth-station/thoth-station.github.io, pull requests merged in 2019-08, with the labels that each got.

#103 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/adviser/searchindex.js
  docs/developers/analyzer/index.html
  docs/developers/analyzer/searchindex.js
  docs/developers/common/index.html
  docs/developers/common/searchindex.js
  docs/developers/lab/index.html
  docs/developers/lab/searchindex.js
  docs/developers/package-extract/_modules/thoth/package_extract/image.html
  docs/developers/package-extract/index.html
  docs/developers/package-extract/searchindex.js
  docs/developers/python/index.html
  docs/developers/python/searchindex.js
  docs/developers/solver/index.html
  docs/developers/solver/searchindex.js
  docs/developers/storages/_modules/index.html
  docs/developers/storages/_modules/thoth/storages/advisers.html
  docs/developers/storages/_modules/thoth/storages/advisers_cache.html
  docs/developers/storages/_modules/thoth/storages/analyses.html
  docs/developers/storages/_modules/thoth/storages/analyses_by_digest.html
  docs/developers/storages/_modules/thoth/storages/analyses_cache.html
  docs/developers/storages/_modules/thoth/storages/base.html
  docs/developers/storages/_modules/thoth/storages/buildlogs.html
  docs/developers/storages/_modules/thoth/storages/buildlogs_analyses.html
  docs/developers/storages/_modules/thoth/storages/buildlogs_analyses_cache.html
  docs/developers/storages/_modules/thoth/storages/ceph.html
  docs/developers/storages/_modules/thoth/storages/ceph_cache.html
  docs/developers/storages/_modules/thoth/storages/dependency_monkey_reports.html
  docs/developers/storages/_modules/thoth/storages/exceptions.html
  docs/developers/storages/_modules/thoth/storages/graph/dgraph.html
  docs/developers/storages/_modules/thoth/storages/graph/models.html
  docs/developers/storages/_modules/thoth/storages/graph/models_base.html
  docs/developers/storages/_modules/thoth/storages/graph/performance.html
  docs/developers/storages/_modules/thoth/storages/inspections.html
  docs/developers/storages/_modules/thoth/storages/observations.html
  docs/developers/storages/_modules/thoth/storages/package_analyses.html
  docs/developers/storages/_modules/thoth/storages/provenance.html
  docs/developers/storages/_modules/thoth/storages/provenance_cache.html
  docs/developers/storages/_modules/thoth/storages/result_base.html
  docs/developers/storages/_modules/thoth/storages/result_schema.html
  docs/developers/storages/_modules/thoth/storages/solvers.html
  docs/developers/storages/_modules/thoth/storages/sync.html
  docs/developers/storages/_modules/voluptuous/schema_builder.html
  docs/developers/storages/_static/documentation_options.js
  docs/developers/storages/genindex.html
  docs/developers/storages/index.html
  docs/developers/storages/objects.inv
  docs/developers/storages/py-modindex.html
  docs/developers/storages/search.html
  docs/developers/storages/searchindex.js
  docs/developers/storages/thoth.storages.graph.html
  docs/developers/storages/thoth.storages.html
Labels: bot, size/XL

#104 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/_modules/thoth/common/openshift.html
  docs/developers/common/genindex.html
  docs/developers/common/index.html
  docs/developers/common/objects.inv
  docs/developers/common/searchindex.js
  docs/developers/common/thoth.common.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/_modules/index.html
  docs/developers/storages/_modules/thoth/storages/advisers.html
  docs/developers/storages/_modules/thoth/storages/advisers_cache.html
  docs/developers/storages/_modules/thoth/storages/analyses.html
  docs/developers/storages/_modules/thoth/storages/analyses_by_digest.html
  docs/developers/storages/_modules/thoth/storages/analyses_cache.html
  docs/developers/storages/_modules/thoth/storages/base.html
  docs/developers/storages/_modules/thoth/storages/buildlogs.html
  docs/developers/storages/_modules/thoth/storages/buildlogs_analyses.html
  docs/developers/storages/_modules/thoth/storages/buildlogs_analyses_cache.html
  docs/developers/storages/_modules/thoth/storages/ceph.html
  docs/developers/storages/_modules/thoth/storages/ceph_cache.html
  docs/developers/storages/_modules/thoth/storages/dependency_monkey_reports.html
  docs/developers/storages/_modules/thoth/storages/exceptions.html
  docs/developers/storages/_modules/thoth/storages/graph/dgraph.html
  docs/developers/storages/_modules/thoth/storages/graph/models.html
  docs/developers/storages/_modules/thoth/storages/graph/models_base.html
  docs/developers/storages/_modules/thoth/storages/graph/performance.html
  docs/developers/storages/_modules/thoth/storages/inspections.html
  docs/developers/storages/_modules/thoth/storages/observations.html
  docs/developers/storages/_modules/thoth/storages/package_analyses.html
  docs/developers/storages/_modules/thoth/storages/provenance.html
  docs/developers/storages/_modules/thoth/storages/provenance_cache.html
  docs/developers/storages/_modules/thoth/storages/result_base.html
  docs/developers/storages/_modules/thoth/storages/result_schema.html
  docs/developers/storages/_modules/thoth/storages/solvers.html
  docs/developers/storages/_modules/thoth/storages/sync.html
  docs/developers/storages/_modules/voluptuous/schema_builder.html
  docs/developers/storages/_static/documentation_options.js
  docs/developers/storages/genindex.html
  docs/developers/storages/index.html
  docs/developers/storages/objects.inv
  docs/developers/storages/py-modindex.html
  docs/developers/storages/search.html
  docs/developers/storages/searchindex.js
  docs/developers/storages/thoth.storages.graph.html
  docs/developers/storages/thoth.storages.html
Labels: bot, size/L

#105 Routine Docs Update
  docs/developers/adviser/_sources/index.rst.txt
  docs/developers/adviser/_sources/performance.rst.txt
  docs/developers/adviser/index.html
  docs/developers/adviser/libdependency_graph.html
  docs/developers/adviser/objects.inv
  docs/developers/adviser/performance.html
  docs/developers/adviser/pipeline.html
  docs/developers/adviser/searchindex.js
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
Labels: bot, size/L

#106 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
Labels: bot, size/S

#107 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
Labels: bot, size/S

#108 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/_modules/thoth/lab/inspection.html
  docs/developers/lab/index.html
  docs/developers/lab/searchindex.js
  docs/developers/lab/thoth.lab.html
  docs/developers/package-extract/_modules/thoth/package_extract/image.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/_modules/thoth/storages/graph/dgraph.html
  docs/developers/storages/index.html
Labels: bot, size/S

#109 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/_modules/thoth/package_extract/image.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
Labels: bot, size/L

#110 Routine Docs Update
  docs/developers/adviser/_images/pipeline.png
  docs/developers/adviser/_sources/index.rst.txt
  docs/developers/adviser/_sources/pipeline.rst.txt
  docs/developers/adviser/_static/pipeline.dia
  docs/developers/adviser/_static/pipeline.png
  docs/developers/adviser/pipeline.html
  docs/developers/adviser/searchindex.js
Labels: bot, size/XXL

#100 Add package-analyzer to the docs listing of repos
  docs/index.html
Labels: approved, size/XS
