Repository thoth-station/thoth-station.github.io, pull requests merged in 2019-05, with the labels that each got.

#19 Provide link to Kebechet in menu
  index.html
Labels: approved, size/XS

#22 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
Labels: bot

#23 Routine Docs Update
  docs/developers/adviser/_modules/index.html
  docs/developers/adviser/_modules/thoth/adviser/python/bin/dependency_graph.html
  docs/developers/adviser/_modules/thoth/adviser/python/pipeline/pipeline.html
  docs/developers/adviser/_modules/thoth/adviser/python/pipeline/step_context.html
  docs/developers/adviser/_modules/thoth/adviser/python/pipeline/step_stats.html
  docs/developers/adviser/_sources/dependency_graph.rst.txt
  docs/developers/adviser/_sources/dependency_monkey.rst.txt
  docs/developers/adviser/_sources/libdependency_graph.rst.txt
  docs/developers/adviser/_sources/pipeline.rst.txt
  docs/developers/adviser/_sources/thoth.adviser.python.bin.rst.txt
  docs/developers/adviser/dependency_graph.html
  docs/developers/adviser/dependency_monkey.html
  docs/developers/adviser/genindex.html
  docs/developers/adviser/index.html
  docs/developers/adviser/libdependency_graph.html
  docs/developers/adviser/objects.inv
  docs/developers/adviser/pipeline.html
  docs/developers/adviser/py-modindex.html
  docs/developers/adviser/searchindex.js
  docs/developers/adviser/thoth.adviser.html
  docs/developers/adviser/thoth.adviser.python.bin.html
  docs/developers/adviser/thoth.adviser.python.html
  docs/developers/adviser/thoth.adviser.python.pipeline.html
  docs/developers/analyzer/index.html
  docs/developers/common/_modules/index.html
  docs/developers/common/_modules/thoth/common/config/base.html
  docs/developers/common/_modules/thoth/common/config/hardware_information.html
  docs/developers/common/_modules/thoth/common/config/operating_system.html
  docs/developers/common/_modules/thoth/common/config/runtime_environment.html
  docs/developers/common/_modules/thoth/common/exceptions.html
  docs/developers/common/_modules/thoth/common/helpers.html
  docs/developers/common/_modules/thoth/common/json.html
  docs/developers/common/_modules/thoth/common/logging.html
  docs/developers/common/_modules/thoth/common/openshift.html
  docs/developers/common/_static/documentation_options.js
  docs/developers/common/genindex.html
  docs/developers/common/index.html
  docs/developers/common/objects.inv
  docs/developers/common/py-modindex.html
  docs/developers/common/search.html
  docs/developers/common/thoth.common.config.html
  docs/developers/common/thoth.common.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/_modules/thoth/storages/graph/dgraph.html
  docs/developers/storages/index.html
Labels: bot

#25 Routine Docs Update
  docs/developers/adviser/_modules/thoth/adviser/python/pipeline/step_context.html
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
  docs/developers/storages/searchindex.js
Labels: bot

#26 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
Labels: bot

#27 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
Labels: bot

#28 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
Labels: bot

#29 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/_modules/index.html
  docs/developers/storages/_modules/thoth/storages/advisers.html
  docs/developers/storages/_modules/thoth/storages/advisers_cache.html
  docs/developers/storages/_modules/thoth/storages/analyses.html
  docs/developers/storages/_modules/thoth/storages/analyses_by_digest.html
  docs/developers/storages/_modules/thoth/storages/analyses_cache.html
  docs/developers/storages/_modules/thoth/storages/base.html
  docs/developers/storages/_modules/thoth/storages/buildlogs.html
  docs/developers/storages/_modules/thoth/storages/ceph.html
  docs/developers/storages/_modules/thoth/storages/ceph_cache.html
  docs/developers/storages/_modules/thoth/storages/dependency_monkey_reports.html
  docs/developers/storages/_modules/thoth/storages/exceptions.html
  docs/developers/storages/_modules/thoth/storages/graph/dgraph.html
  docs/developers/storages/_modules/thoth/storages/graph/models.html
  docs/developers/storages/_modules/thoth/storages/graph/models_base.html
  docs/developers/storages/_modules/thoth/storages/inspections.html
  docs/developers/storages/_modules/thoth/storages/observations.html
  docs/developers/storages/_modules/thoth/storages/provenance.html
  docs/developers/storages/_modules/thoth/storages/provenance_cache.html
  docs/developers/storages/_modules/thoth/storages/result_base.html
  docs/developers/storages/_modules/thoth/storages/result_schema.html
  docs/developers/storages/_modules/thoth/storages/solvers.html
  docs/developers/storages/_modules/thoth/storages/sync.html
  docs/developers/storages/_modules/voluptuous/schema_builder.html
  docs/developers/storages/_static/documentation_options.js
  docs/developers/storages/genindex.html
  docs/developers/storages/index.html
  docs/developers/storages/objects.inv
  docs/developers/storages/py-modindex.html
  docs/developers/storages/search.html
  docs/developers/storages/searchindex.js
  docs/developers/storages/thoth.storages.graph.html
  docs/developers/storages/thoth.storages.html
Labels: bot

#30 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/_modules/thoth/solver/python/python.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
Labels: bot

#31 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/_modules/thoth/solver/python/python.html
  docs/developers/solver/index.html
  docs/developers/storages/_modules/thoth/storages/graph/dgraph.html
  docs/developers/storages/index.html
Labels: bot

#32 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/_modules/thoth/common/openshift.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
Labels: bot, size/S

#33 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
Labels: bot, size/S

#34 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
Labels: bot, size/S

#35 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
Labels: bot, size/S

#36 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
Labels: bot, size/S

#37 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/_modules/index.html
  docs/developers/storages/_modules/thoth/storages/advisers.html
  docs/developers/storages/_modules/thoth/storages/advisers_cache.html
  docs/developers/storages/_modules/thoth/storages/analyses.html
  docs/developers/storages/_modules/thoth/storages/analyses_by_digest.html
  docs/developers/storages/_modules/thoth/storages/analyses_cache.html
  docs/developers/storages/_modules/thoth/storages/base.html
  docs/developers/storages/_modules/thoth/storages/buildlogs.html
  docs/developers/storages/_modules/thoth/storages/ceph.html
  docs/developers/storages/_modules/thoth/storages/ceph_cache.html
  docs/developers/storages/_modules/thoth/storages/dependency_monkey_reports.html
  docs/developers/storages/_modules/thoth/storages/exceptions.html
  docs/developers/storages/_modules/thoth/storages/graph/dgraph.html
  docs/developers/storages/_modules/thoth/storages/graph/models.html
  docs/developers/storages/_modules/thoth/storages/graph/models_base.html
  docs/developers/storages/_modules/thoth/storages/inspections.html
  docs/developers/storages/_modules/thoth/storages/observations.html
  docs/developers/storages/_modules/thoth/storages/provenance.html
  docs/developers/storages/_modules/thoth/storages/provenance_cache.html
  docs/developers/storages/_modules/thoth/storages/result_base.html
  docs/developers/storages/_modules/thoth/storages/result_schema.html
  docs/developers/storages/_modules/thoth/storages/solvers.html
  docs/developers/storages/_modules/thoth/storages/sync.html
  docs/developers/storages/_modules/voluptuous/schema_builder.html
  docs/developers/storages/_static/documentation_options.js
  docs/developers/storages/genindex.html
  docs/developers/storages/index.html
  docs/developers/storages/objects.inv
  docs/developers/storages/py-modindex.html
  docs/developers/storages/search.html
  docs/developers/storages/thoth.storages.graph.html
  docs/developers/storages/thoth.storages.html
Labels: bot, size/L

#38 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
Labels: bot, size/S

#39 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
Labels: bot, size/S
