Repository thoth-station/thoth-station.github.io, pull requests merged in 2019-04, with the labels that each got.

#4 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/adviser/searchindex.js
  docs/developers/analyzer/index.html
  docs/developers/analyzer/searchindex.js
  docs/developers/common/index.html
  docs/developers/common/searchindex.js
  docs/developers/lab/index.html
  docs/developers/lab/searchindex.js
  docs/developers/package-extract/index.html
  docs/developers/package-extract/searchindex.js
  docs/developers/python/index.html
  docs/developers/python/searchindex.js
  docs/developers/solver/index.html
  docs/developers/solver/searchindex.js
  docs/developers/storages/_modules/thoth/storages/graph/models.html
  docs/developers/storages/genindex.html
  docs/developers/storages/index.html
  docs/developers/storages/objects.inv
  docs/developers/storages/searchindex.js
  docs/developers/storages/thoth.storages.graph.html
Labels: approved, bot, size/M

#6 Routine Docs Update
  docs/developers/adviser/_modules/thoth/adviser/isis.html
  docs/developers/adviser/genindex.html
  docs/developers/adviser/index.html
  docs/developers/adviser/objects.inv
  docs/developers/adviser/searchindex.js
  docs/developers/adviser/thoth.adviser.html
  docs/developers/analyzer/index.html
  docs/developers/common/_modules/thoth/common/logging.html
  docs/developers/common/_modules/thoth/common/openshift.html
  docs/developers/common/index.html
  docs/developers/common/objects.inv
  docs/developers/common/thoth.common.html
  docs/developers/lab/_modules/thoth/lab/utils.html
  docs/developers/lab/_sources/thoth.lab.rst.txt
  docs/developers/lab/genindex.html
  docs/developers/lab/index.html
  docs/developers/lab/objects.inv
  docs/developers/lab/py-modindex.html
  docs/developers/lab/searchindex.js
  docs/developers/lab/thoth.lab.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
Labels: bot, size/XL

#5 Add auto-gate for Nepthy's automatic docs update
  .zuul.yaml
Labels: approved, size/XS

#8 Routine Docs Update
  docs/developers/adviser/_modules/thoth/adviser/python/bin/dependency_graph.html
  docs/developers/adviser/_modules/thoth/adviser/python/solver.html
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
Labels: bot, size/S

#9 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
Labels: bot, size/S

#10 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
Labels: bot, size/S

#11 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
Labels: bot, size/S

#12 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
Labels: bot, size/S

#14 Routine Docs Update
  docs/developers/adviser/_modules/thoth/adviser/python/pipeline/pipeline.html
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/_modules/thoth/storages/graph/dgraph.html
  docs/developers/storages/index.html
Labels: bot, size/M

#15 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/_modules/thoth/python/package_version.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
Labels: bot, size/S

#16 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
Labels: bot, size/S

#17 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
Labels: bot, size/S

#18 Routine Docs Update
  docs/developers/adviser/index.html
  docs/developers/analyzer/index.html
  docs/developers/common/index.html
  docs/developers/lab/index.html
  docs/developers/package-extract/index.html
  docs/developers/python/index.html
  docs/developers/solver/index.html
  docs/developers/storages/index.html
Labels: bot, size/S
