Repository thoth-station/thoth-station.github.io, pull requests merged in 2020-09, with the labels that each got.

#116 Add justification document for TensorFlow21Urllib3Step unit
  _justifications/tf_21_urllib3.md
Labels: size/M

#115 Add justification template
  _justifications/example.md.template
Labels: size/M

#119 Provide justification information for CPU time exceeded message
  _j/cpu_time_exceeded.md
Labels: size/M

#118 Provide justification information for OOM
  _j/oom.md
Labels: size/M

#124 Provide justification information when no observations are shown
  _j/no_observations.md
Labels: size/M

#125 Provide justification information for no_semantic_interposition
  _j/no_semantic_interposition.md
Labels: size/M

#121 Provide justification information for errored out advises
  _j/error_logs.md
Labels: size/M

#120 Provide justification information for AVX2 optimized AICoE TF builds
  _j/aicoe_tf_avx2.md
Labels: size/M

#122 Provide justification information for intel-tensorflow
  _j/intel_tensorflow.md
Labels: size/M

#126 Provide justification information for security
  _j/security.md
Labels: size/M

#127 Provide justification document for unresolved messages
  _j/unresolved.md
Labels: size/M

#123 Provide justification information for mkl-threads
  _j/mkl_threads.md
Labels: size/M

#132 Add justification document for tf_42045
  _j/tf_42045.md
Labels: size/M

#133 Reheadline
  .gitignore
  justifications.markdown
Labels: size/XS

#134 Add justification document for tf_42045
  _j/tf_40584.md
Labels: size/M

#131 Add advised manifest changes to the justification document template
  _j/example.md.template
  recommendation_types.markdown
Labels: approved, size/M

#117 Add .gitignore
  .gitignore
Labels: do-not-merge/needs-rebase, size/XS

#140 Move example justification so it can be still renderred locally
  _config.yml
  _j/_example.md
Labels: approved, size/XS

#141 Add justification for mkl-libs
  _j/mkl_libs.md
Labels: size/M

#139 Add advised manifest changes section for mkl_threads justification
  _j/mkl_threads.md
Labels: approved, size/XS

#142 Add justification for tf_cuda
  _j/tf_cuda.md
Labels: approved, size/M

#143 Add justification for latest_hops
  _j/latest_hops.md
Labels: approved, size/M

#144 Add no_paths justification
  _j/no_paths.md
Labels: approved, size/M

#146 Fix curl listing and break long lines in console output
  _j/error_logs.md
  _j/no_observations.md
Labels: approved, size/S

#147 Add justification document for tf_no_cuda
  _j/tf_no_cuda.md
Labels: approved, size/M

#148 Add justification for unknown CUDA version
  _j/tf_unknown_cuda.md
Labels: approved, size/M

#155 Add a justification for CVE
  _j/cve.md
Labels: approved, size/M

#154 Add justification for backports
  _j/backports.md
Labels: approved, size/M

#158 Add justification for tf_25636
  _j/tf_25636.md
Labels: size/M

#157 Add justification for solved_sw_env
  _j/solved_sw_env.md
Labels: size/M

#156 Add justification for solve_direct
  _j/solve_direct.md
Labels: size/M

#153 Add justification for spec_env
  _j/spec_env.md
Labels: size/M

#152 Add justification for no-dev
  _j/no_dev.md
Labels: size/M

#151 Add justification for rm_user_stack
  _j/rm_user_stack.md
Labels: size/M

#150 Add user-stack justification
  _j/user_stack.md
Labels: size/M

#149 Add a justification about an unknown TensorFlow release
  _j/cuda_unknown_tf.md
Labels: size/M

#145 Add justification document describing no stack produced error
  _j/no_stack.md
Labels: size/L

#159 Add justification for tf_114_gast
  _j/tf_114_gast.md
Labels: approved, size/M

#160 added GA code
  _config.yml
  home.markdown
Labels: approved, size/M

#163 Add justification for tf_41902
  _j/tf_41902.md
Labels: size/M

#162 Be more specific on how CVE database is updated
  _j/cve.md
Labels: size/XS

#161 Add justification for tf_41866
  _j/tf_41866.md
Labels: size/M

#164 Link Python documentation for backports
  _j/backports.md
Labels: approved, size/S

#165 Add justification for Pandas>=1.2 dropping Python 3.6 support
  _j/pandas_py_36_drop.md
Labels: approved, size/M

#166 Warn that the stack supplied by the user is not checked
  _j/user_stack.md
Labels: approved, size/XS

#167 Add specification document for py_version
  _j/py_version.md
Labels: approved, size/M

#168 Add platform justification document
  _j/platform.md
Labels: approved, size/M

#169 Add justification for RHEL minor versions
  _j/rhel_version.md
Labels: approved, size/M

#171 Provide justification for missing ABI symbols
  _j/abi_missing.md
Labels: approved, size/M

#172 Add justification for tf_intel
  _j/tf_intel.md
Labels: approved, size/M

#173 Add also IntelTensorFlowCPUPseudonym pipeline unit
  _j/tf_intel.md
Labels: approved, size/XS

#174 Add justification for tf_cuda_alt
  _j/tf_cuda_alt.md
Labels: approved, size/M
