Repository thoth-station/thoth-station.github.io, pull requests merged in 2020-11, with the labels that each got.

#179 Add justification for tf-py39 sieve
  _j/tf_py39.md
Labels: approved, size/M

#180 Add justification for tf_21_h5py
  _j/tf_21_h5py.md
Labels: approved, size/M

#181 TensorFlow 2.3 will not support Python 3.9
  _j/tf_py39.md
Labels: approved, size/XS

#183 add doc for bandit justification
  _j/si_bandit.md
Labels: approved, size/M

#184 Add justification for TensorFlow API symbols
  _j/tf_api.md
  _j/tf_no_api.md
Labels: approved, size/L

#185 Add justification for Thamos timeout
  _j/thamos_timeout.md
Labels: size/M

#186 h5py can cause issues also on TensorFlow 2.3
  _j/tf_21_h5py.md
Labels: approved, size/S

#187 Add justification for tf_38518
  _j/tf_38518.md
Labels: approved, size/M

#188 Add justification for slow Keras embedding layer
  _j/tf_42475.md
Labels: approved, size/M
